"""Shared B2C / consumer-company detection logic.

Used by all scraper modules to ensure we only keep companies
that are genuinely consumer-facing and would benefit from marketing.
"""

import re

# Description keywords that signal consumer-facing company needing marketing
CONSUMER_SIGNALS = [
    r"\bconsumer\b",
    r"\bb2c\b",
    r"\bapp for (people|users|consumers|everyone|individuals|families|parents|students|shoppers|women|men|couples|renters|homeowners|patients|travelers|riders|drivers|freelancers)\b",
    r"\bmarketplace\b",
    r"\bshopping\b",
    r"\be-?commerce\b",
    r"\bonline store\b",
    r"\bsocial (network|media|platform|app|commerce)\b",
    r"\bdating\b",
    r"\bfood (delivery|ordering|app|tech)\b",
    r"\bgrocery\b",
    r"\bmeal (kit|prep|delivery)\b",
    r"\bfitness\b",
    r"\bworkout\b",
    r"\bwellness\b",
    r"\bhealth(care)?\s+(app|platform|for (consumers|patients|people|everyone))\b",
    r"\btelehealth\b",
    r"\btherapy\b",
    r"\btherapist\b",
    r"\bmental\s*health\b",
    r"\bmeditation\b",
    r"\btravel\b",
    r"\bbooking\b",
    r"\bvacation\b",
    r"\bhotel\b",
    r"\bflight\b",
    r"\bmusic\b",
    r"\bgaming\b",
    r"\bgame\b",
    r"\bstreaming\b",
    r"\bpodcast\b",
    r"\bpersonal\s+finance\b",
    r"\bbudget(ing)?\b",
    r"\binvest(ing|ment)?\s+(app|platform|for everyone|for beginners|made easy)\b",
    r"\brobinhood\b",
    r"\bcredit\s+(card|score|build)\b",
    r"\bsav(e|ing)\s+money\b",
    r"\bneobank\b",
    r"\bdigital\s+bank\b",
    r"\binsurance\s+for\s+(individuals|people|everyone|renters|pet|car|health)\b",
    r"\bpet(s|\s+care|\s+food|\s+insurance|\s+health)\b",
    r"\bdog\b",
    r"\bcat\b",
    r"\bkid(s|\'s)\b",
    r"\bparents?\b",
    r"\bfamily\b",
    r"\bbaby\b",
    r"\bstudent\b",
    r"\bcollege\b",
    r"\bfashion\b",
    r"\bbeauty\b",
    r"\bskincare\b",
    r"\bclothing\b",
    r"\bapparel\b",
    r"\bjewelry\b",
    r"\bdelivery\b",
    r"\brental(s)?\b",
    r"\brent(ing)?\s+(apartment|home|car)\b",
    r"\bhome(owners?|buyers?|buying)\b",
    r"\bmortgage\b",
    r"\breal\s+estate\s+(for|platform|app|marketplace)\b",
    r"\btutoring\b",
    r"\blearning (app|platform)\b",
    r"\beducation\s+(app|platform|for)\b",
    r"\blanguage\s+learning\b",
    r"\bcreator\b",
    r"\binfluencer\b",
    r"\bcontent\s+creator\b",
    r"\bphoto\s+(sharing|editing|app)\b",
    r"\bvideo\s+(sharing|editing|app|platform)\b",
    r"\bshort[\s-]form\s+video\b",
    r"\bwedding\b",
    r"\brecipe\b",
    r"\bcooking\b",
    r"\brestaurant\s+(discovery|booking|reservation|review)\b",
    r"\bcoffee\b",
    r"\brideshare?\b",
    r"\bcarpool\b",
    r"\btaxi\b",
    r"\belectric\s+vehicle\b",
    r"\bev\s+charg\b",
    r"\bcar\s+(buying|insurance|rental|sharing)\b",
    r"\bpokemon\b",
    r"\bcollectibles?\b",
    r"\bsports\s+(betting|fan|card|ticket)\b",
    r"\bticket(s|ing)?\b",
    r"\bevent(s)?\s+(discovery|ticket|booking|planning)\b",
    r"\bnews\b",
    r"\bpublishing\b",
    r"\bnewsletter\b",
    r"\bsecondhand\b",
    r"\bresale\b",
    r"\bthrift\b",
    r"\bvintage\b",
    r"\bused\s+(car|clothes|goods)\b",
    r"\bauction\b",
    r"\bluxury\b",
    r"\bwine\b",
    r"\balcohol\b",
    r"\bcannabis\b",
    r"\bremittance\b",
    r"\bmoney\s+transfer\b",
    r"\bpay(ment)?\s+(app|for|split)\b",
    r"\bcashback\b",
    r"\breward(s)?\b",
    r"\bloyalty\b",
    r"\bcoupon\b",
    r"\bdiscount\b",
    r"\bcharity\b",
    r"\bdonat(e|ion)\b",
    r"\bfundraising\b",
    r"\bcrowdfunding\b",
    r"\bproperty\s+(management|rental|listing)\b",
]

# Keywords that strongly indicate B2B / enterprise — NOT consumer
B2B_EXCLUSION_SIGNALS = [
    r"\b(enterprise|b2b)\b",
    r"\bfor (companies|businesses|teams|enterprises|developers|startups|employers|recruiters|agencies|firms|hospitals|clinics|banks|insurers|manufacturers|retailers|brands|merchants|fleets|warehouses|factories|suppliers|vendors|contractors|accountants|lawyers|law firms|pharma)\b",
    r"\bsaas\b",
    r"\bdev(ops|eloper)?\s*(tool|platform|infra|framework)\b",
    r"\binfrastructure\b",
    r"\bapi\s+(for|platform|layer|gateway)\b",
    r"\bsdk\b",
    r"\bsupply\s*chain\b",
    r"\bcompliance\b",
    r"\bsalesforce\b",
    r"\bcrm\s+(for|platform|software)\b",
    r"\berp\b",
    r"\bwarehouse\s+(management|automation|robot)\b",
    r"\blogistics\s+(platform|software|optimization)\b",
    r"\bprocurement\b",
    r"\bvendor\s+management\b",
    r"\bsecurity\s+(platform|tool|for|monitoring|scanning)\b",
    r"\bcyber\s*security\b",
    r"\bcloud\s+(infra|platform|computing|native)\b",
    r"\borchestrat(e|ion)\b",
    r"\bcode\s+review\b",
    r"\bci[\s/]+cd\b",
    r"\bdata\s+(pipeline|warehouse|lake|platform|engineering|infra)\b",
    r"\bpayroll\b",
    r"\bhr\s+(platform|software|tool)\b",
    r"\baccounting\s+(software|platform|tool)\b",
    r"\bbookkeeping\b",
    r"\binvoic(e|ing)\s+(software|platform|tool)\b",
    r"\bdefense\s+(tech|contractor)\b",
    r"\bmilitary\b",
    r"\bgovernment\s+(contractor|tech|software)\b",
    r"\bsatellite\b",
    r"\bspace\s+(vehicle|craft|tech|defense)\b",
    r"\bdrug\s+discovery\b",
    r"\bclinical\s+trial\b",
    r"\blab\s+automation\b",
    r"\bmanufactur(ing|er)\b",
    r"\bindustrial\b",
    r"\brobotic(s)?\s+(arm|warehouse|factory)\b",
    r"\bnuclear\b",
    r"\bsemiconductor\b",
    r"\bchip\s+design\b",
    r"\bfoundry\b",
    r"\bLLM\s+(infra|deploy|serving|hosting)\b",
    r"\bmodel\s+(training|serving|deployment|fine-?tun)\b",
    r"\bvector\s+database\b",
    r"\bembedding\b",
    r"\bworkflow\s+automation\b",
    r"\bbilling\s+(software|platform|infra)\b",
    r"\bfraud\s+(detection|prevention)\b",
    r"\bKYC\b",
    r"\bAML\b",
    r"\bregulatory\b",
    r"\baudit\b",
    r"\btax\s+(software|platform|compliance|filing)\b",
]

# Card-level tags from YC that indicate consumer
CONSUMER_CARD_TAGS = {
    "consumer",
    "b2c",
    "marketplace",
    "social",
    "media",
    "entertainment",
    "gaming",
    "food & beverage",
    "food",
    "travel",
    "fitness",
    "wellness",
    "health & wellness",
    "e-commerce",
    "ecommerce",
    "retail",
    "education",
    "edtech",
    "music",
    "sports",
    "fashion",
    "beauty",
    "dating",
    "real estate",
    "proptech",
    "grocery",
    "delivery",
    "mobility",
    "transportation",
    "home",
    "family",
    "pets",
    "personal finance",
    "creator economy",
    "creator",
    "community",
}


def is_consumer_company(card_text: str, description: str) -> bool:
    """Return True if the company is consumer-facing and likely needs marketing."""
    text_lower = card_text.lower()
    desc_lower = description.lower()
    combined = f"{text_lower} {desc_lower}"

    # Hard B2B exclusion — if clearly enterprise, skip
    is_b2b = any(
        re.search(p, combined, re.IGNORECASE)
        for p in B2B_EXCLUSION_SIGNALS
    )

    # Check card-level category tags (short uppercase text from YC)
    for tag in CONSUMER_CARD_TAGS:
        if tag in text_lower:
            return not is_b2b

    # Check description for consumer signals
    has_consumer_signal = any(
        re.search(p, combined, re.IGNORECASE)
        for p in CONSUMER_SIGNALS
    )

    if has_consumer_signal and not is_b2b:
        return True

    return False
